# Site settings
title: John Cobb
email: jcobb2@math.wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  Second year PhD Student at UW Madison.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johndcobb.github.io" # the base hostname & protocol for your site
production_url: "https://johndcobb.github.io"
github_username: johndcobb
permalink: /blog/:year/:month/:title.html

twitter:
  username: cobbjd3

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
