# Site settings
title: John Cobb
email: jcobb2@math.wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  NSF Postdoc at the Mathematics Department at Auburn University. I am interested in algebraic geometry, commutative algebra, and their applications to data science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johndcobb.github.io" # the base hostname & protocol for your site
production_url: "https://johndcobb.github.io"
github_username: johndcobb
permalink: /blog/:year/:month/:title.html

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
