- title: Organizer
  at: UW Madison Graduate Algebraic Geometry Seminar
  url: "https://hilbert.math.wisc.edu/wiki/index.php/Graduate_Algebraic_Geometry_Seminar"
  location: Madison, WI
  years: Fall 2021 -
  description: "The purpose of this seminar is to learn algebraic geometry and commutative algebra by giving and listening to talks in a informal setting."
- title: Public Service Fellow
  at: University of Wisconsin-Madison
  url: https://wiscience.wisc.edu/program/public-service-fellows
  location: Madison, WI
  years: Jan 2021-Jan 2022
  description: The 2021 cohort had 3 people in the social entrepreneurship pathway. Over the course of a year, fellows engage in a practicum working directly with a community partner on a chosen project focused on issues of public concern.
- title: Mentor
  at:  First Generation Student Success
  url: https://firstgensuwmadison.wixsite.com/fgss
  location: Madison, WI
  years: Fall 2020-Spring 2021
  description: "FGSS is a student organization dedicated to helping students locate resources, connect with peers and faculty, and support them along their college journey. FGSS links first-generation college students to first generation graduate and faculty mentors for monthly meetings. "
- title: Geometry of Schemes Reading Group
  at: UW Madison
  url: https://johndcobb.github.io/organization/geometryofschemes/
  location: Madison, WI
  years: Summer 2020
  description: "Organizer, Book: Geometry of Schemes by Eisenbud and Harris."
- title: Organizer
  at: UW Madison Directed Reading Program 
  url: https://sites.google.com/site/uwmadisondrp/
  location: Madison, WI
  years: Fall 2019-
  description: "The DRP is a math mentoring program that pairs undergraduate students with graduate student mentors, for a semester-long independent study project. The goal of this program is to get students excited about mathematics by giving them an out-of-the-classroom experience, usually in topics that are outside of their coursework."
- title: Volunteer
  at: AMS Fall Central Sectional
  years: Sep 2019
  location: Madison, WI
  description: "Signed in attendees to the 3-day AMS Fall central sectional meeting."
- title: Student Ambassador
  at: College of Charleston School of Sciences and Mathematics
  years: Sep 2018-May 2019
  location: Charleston, SC
  description: Select group of 9 students who have demonstrated outstanding academic achievement and exemplar student leadership. Represent the School of Sciences and Mathematics at College of Charleston to incoming students and other interest groups
- title: Student Vice President & Webmaster
  at: Phi Kappa Phi
  years: Apr 2017-May 2019
  location: Charleston, SC
  description: Met with board to coordinate volunteer opportunities and promote education throughout the College of Charleston campus. Helped organize events on campus for Phi Kappa Phi members. Managed the College of Charleston Chapter Phi Kappa Phi Website.
- title: Volunteer
  at: AMS Spring Southeastern Sectional Meeting
  years: Mar 2017
  location: Charleston, SC
  description: "Signed in attendees to the 3-day AMS Spring southeastern sectional meeting."
- title: Volunteer
  at: College of Charleston Math Meet
  years: 2016-2018
  url: https://mathmeet.cofc.edu/
  location: Charleston, SC
  description: "Volunteered to oversee various parts of the planned activities including judging timed sprints and signing students in."
- title: Volunteer Tutor
  at: Trident Literacy Association
  years: Oct 2015-Oct 2016
  url: https://tridentlit.org/
  location: Charleston, SC
  description: "Trident literacy is a nonprofit organization that seeks to reverse the cycle of generational poverty and illiteracy. Helped weekly to prepare nontraditional students for their GED. Primarily taught topics from arithmetic, algebra, and precalculus."
- title: Cofounder & Board Member
  at: The Cancer Chase
  years: Feb 2015-Oct 2017
  url: https://cancerchase5k.racesonline.com/
  location: Fort Mill, SC
  description: "Helped direct the founding of The Cancer Chase, whose first project began an annual 5k run benefiting Carolinas HealthCare System’s Levine Cancer Institute. Rallied support from local businesses to raise over $15,000 annually."
  